### ISSUE TITLE
converting 3D volume (e.g. brain mask) still requires bvec and bval

### ISSUE THREAD

**Issue by zhangfanmark** [pnlbwh/conversion#21]
Hi @tashrifbillah 

It would be good to set --bvec an --bval as optimal parameters in nhdr_write.py, so when converting a 3D volume does not require these input parameters.

Regards,
Fan

**Comment by tashrifbillah** [comment]
They were optional from the beginning
https://github.com/pnlbwh/conversion/blob/48f94ce21005d1af779f98df0c5ea8ec0e204835/conversion/nhdr_write.py#L146-L148
