### ISSUE TITLE
nifit_write.py outputs empty bvec bval files

### ISSUE THREAD

**Issue by ahilderley** [pnlbwh/conversion#23]
When converting from nrrd to nii, the bvec and bval files are empty. The nifti file looks correct. Any suggestions?

**Comment by tashrifbillah** [comment]
Post the NRRD header here?

**Comment by ahilderley** [comment]
The file is an output of DTIprep.
[header.txt](https://github.com/pnlbwh/conversion/files/8336636/header.txt)

**Comment by tashrifbillah** [comment]
Hmm I agree with you, it is surprising. What command did you try?

**Comment by ahilderley** [comment]
nifti_write.py -i dwi.nrrd -p dwi

The output nifti is great, but dwi.bvec and dwi.bval are empty files.

**Comment by tashrifbillah** [comment]
Okay I tried but couldn't realize the problem. How about you dropbox me the NRRD so I can investigate it through Python debugger?
`tbillah[at]bwh[dot]harvard[dot]edu`

**Comment by ahilderley** [comment]
I can't share the NRRD, as these are patient scans. 
I'll continue trying with other files, or revert to DWIConvert. 
Thank you for your help.
